---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
    filters: 
      metadata: 
        deployment_name: QA
  register: result
- debug:
    msg:
      - "Hostname: {{ item.hostname }}"
      - "Metadata: {{ item.metadata }}"
  with_items: "{{result.openstack_servers}}"
   
