---
# tasks file for roles/osp-instance-delete
- name: Fetch all QA Instance Info
  os_server_info:
    cloud: openstack
    filters: 
      metadata: 
        deployment_name: QA
  register: result
- name: Delete all QA instances by id
  os_server:
    cloud: openstack
    name: "{{ item.id }}"
    state: absent
  with_items: "{{result.openstack_servers}}"
   
