---
# lb-tier/tasks

- name: Install load balancer packages
  package:
    name: "{{ load_balancer_packages }}"
    state: present
  tags:
    - lbs
    - haproxy

- name: Configure haproxy load balancing
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  tags:
    - lbs
    - haproxy
  notify: restart_haproxy

- name: Enable Haproxy
  service:
    name: haproxy
    state: started
    enabled: true
  tags:
    - lbs
    - haproxy

