---
- name: Create instance app2
  os_server:
    cloud: openstack
    name: "{{osp_servers.app2.name}}"
    state: "{{osp_servers.app2.state}}"
    image: "{{osp_servers.app2.image}}"
    key_name: "{{osp_servers.app2.key_name}}"
    flavor: "{{osp_servers.app2.flavor}}"
    security_groups: "{{osp_servers.app2.security_group}}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "{{osp_servers.app2.meta}}"
    userdata: |
      #cloud-config
      users:
        - name: cloud-user
          ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBTCYfp/LvJHpyMqZBeXoX/jHz/LB4yAeRBMYLf3V/kopcIetQQHYIkgW96LB9CmQABX9heoopsDK8tj5IZgz//dPqfYapm+S4mz8jIOFvIwmUle6iM2KdBvMGqIBKiURVoTwQZZMoWzZEqmaHFrRuNrZCDUJ8B3LmNBqp3UQtnYUuG2Vtg/q94Wqlv7nGiBJ/bT0HhPjrsFGXJs29F354rK3Xp9KeKO9RB2PYNgIJ22KFNOZ3IV67I5bd2uJQXHEuQYqAenHh/cIt1GicOVGHKr9RQOngz4093/tuVfiwhIyKZVWu4Xm3G8x6v9nyg4ifi5XSBNvXBCuXSdivv+yd

# app2.yml
