---
- name: Create instance app2
  os_server:
    cloud: openstack
    name: "{{osp_servers.app2.name}}"
    state: "{{osp_servers.app2.state}}"
    image: "{{osp_servers.app2.image}}"
    key_name: "{{osp_servers.app2.key_name}}"
    flavor: "{{osp_servers.app2.flavor}}"
    security_groups: "{{osp_servers.app2.security_group}}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "{{osp_servers.app2.meta}}"
    userdata: |
      #cloud-config
      ssh_keys:
        rsa_private: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAwUwmH6fy7yR6cjKmQXl6F/4x8/yweMgHkQTGC391f5KKXCHr
          UEB2CJIFveiwfQpkAAV/YXqKKbAyvLY+SGYM//3T6n2GqZvkuJs/IyDhbyMJlJXu
          ojNinQbzBqiASolEVaE8EGWTKFs2RKpmhxa0bja2Qg1CfAdy5jQaqd1ELZ2FLhtl
          bYP6veFqpb+5xogSf209B4T467BRlybNvRd+eKyt16fSnijvUQdj2DYCCdtihTTm
          dyFeuyOW3driUFxxLkGKgHpx4f3CLdRonDlRhyq/UUDp4M+NPd/7blX4sISMimVV
          ruF5txvMer/Z8oOIn4uV0gTb1wQrl0nYr7/snQIDAQABAoIBABw9qug/GnA0DSu4
          GLBCNkNhIR07kvDikLBwWRr+8UTFPS++yOl9sYEJDIu1fmuWZAvYwcaVJ7B1jMQj
          gDAFsOqJxDdjRZRsMVuDWxMfz6/0F4c87JOIHGVCyaj0X2IEchZsqyDeJkTkJqab
          msUr3QqpNbGqzEbgs7nMbQTaTga31r0SY2IND0p8BfheUfAEZz5Q9EWIoeAvjL8v
          3apSO+ffRzzJy3Z40m3ZxKRVq5pDEzfWPYKkzKsTH/n2kzs40RYDNoTt6Hcpc000
          oV2pz5sNrbHcT77G411dQd5c2Fa0k9rgx5DHIxx2w4/Mlq6ufaYAWOO9kwXGHN1I
          tOvKyCUCgYEA7weJ4RrHdwLv0TbQamYkXg0Mvkg4Ffiafv2CssVb54NzzAtjktD5
          WNz9C3sCe3JyS6DQXJEOLpXAWOcwT3QfOPeJUFVVibkB5v07FAM6VShCACyaeQ8/
          NNyrQldnsVtLuf3aiHUH+AXuh2LuFEQX5/bhBvqI03dO3EHASDvsyyMCgYEAzwVp
          ewHY5j0q9plN12bZvRcRNM7xkjX304r/+aY3bRYF0BHp7WSjrejmQ8Y9ZKNeyHoa
          jNDrE0Yy2RXMoWkH+rmPHovPqTiSxSsX1NEqDQEcU+O1ISRgPivgjQnPl+a/9Z1l
          VQ7kcdkfy0tPO5TGk1uV66QclynAM4SNHV24xT8CgYEAnQ3R/XMv/jWSx1+Bv3dP
          i/B9IAWpvF31fV0q5DWi9lI74qTVDyF5xHanWUTA08XV7XVDkp7It7kzgfadmocN
          AMw8j+kR5AUIh/J5P+QDDvL9ssmb0dE/0YbwjA2MF0+KSTHPxftHeiLDoHdTQUOg
          hYyEPKafAnsQ+M3G/m9JXgsCgYBcHkJjc9z6BnnZpTnYAXIeC+eiIfuoXc9bGFzy
          z52WMth/T5lSAxg6SIo92jZzU6bXek3aHxSbTP9PTb3yjPP6AxvGMdxDpmLYzWYb
          Ur9tbfMW+RoeFzukLo4K9DSlmQ4N0u3GPYw1hLH7GhW1o2wBIh3B7xKxyOg3hGHu
          kUeorQKBgQC684OaGy2X1MO+iiIv0YgkCjECdyFMLtAjEp2nPDqu42/QE5gxzEq4
          mAj94U2I2/DUBCKvlSwB2a+n6vkgWgkOMkbfi6jYC5J3ktrMqK4pWWQ/GPSijekt
          ZFQOKTpno3xXhUsz9Ts4shClaG+BscqHeX0yfs1hknbsCSNuCnZxmQ==
          -----END RSA PRIVATE KEY-----
        rsa_public: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBTCYfp/LvJHpyMqZBeXoX/jHz/LB4yAeRBMYLf3V/kopcIetQQHYIkgW96LB9CmQABX9heoopsDK8tj5IZgz//dPqfYapm+S4mz8jIOFvIwmUle6iM2KdBvMGqIBKiURVoTwQZZMoWzZEqmaHFrRuNrZCDUJ8B3LmNBqp3UQtnYUuG2Vtg/q94Wqlv7nGiBJ/bT0HhPjrsFGXJs29F354rK3Xp9KeKO9RB2PYNgIJ22KFNOZ3IV67I5bd2uJQXHEuQYqAenHh/cIt1GicOVGHKr9RQOngz4093/tuVfiwhIyKZVWu4Xm3G8x6v9nyg4ifi5XSBNvXBCuXSdivv+yd
      yum_repos:
        rhel-7-server-rpms:
          baseurl: http://192.168.0.5/repos/rhel-7-server-rpms
          enabled: true
          gpgcheck: false
          name: Red Hat Enterprise Linux 7
        rhel-7-server-rh-common-rpms:
          baseurl: http://192.168.0.5/repos/rhel-7-server-rh-common-rpms
          enabled: true
          gpgcheck: false
          name: Red Hat Enterprise Linux 7 Common
        rhel-7-server-extras-rpms:
          baseurl: http://192.168.0.5/repos/rhel-7-server-extras-rpms
          enabled: true
          gpgcheck: false
          name: Red Hat Enterprise Linux 7 Extras
        rhel-7-server-optional-rpms:
          baseurl: http://192.168.0.5/repos/rhel-7-server-optional-rpms
          enabled: true
          gpgcheck: false
          name: Red Hat Enterprise Linux 7 Optional

# app2.yml
