---
- name: Add floating IP to frontend
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: frontend
    network: ext_network
    wait: true
    timeout: 200
- name: Add floating IP to app1
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: app1
    network: ext_network
    wait: true
    timeout: 200
- name: Add floating IP to app2
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: app2
    network: ext_network
    wait: true
    timeout: 200
- name: Add floating IP to db
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: db
    network: ext_network
    wait: true
    timeout: 200

# floating-ip.yml
