---
- name: Create instance frontend
  os_server:
    cloud: openstack
    name: "{{osp_servers.frontend.name}}"
    state: "{{osp_servers.frontend.state}}"
    image: "{{osp_servers.frontend.image}}"
    key_name: "{{osp_servers.frontend.key_name}}"
    flavor: "{{osp_servers.frontend.flavor}}"
    security_groups: "{{osp_servers.frontend.security_group}}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "{{osp_servers.frontend.meta}}"
    userdata: |
      #cloud-config
      users:
        - name: cloud-user
          ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBTCYfp/LvJHpyMqZBeXoX/jHz/LB4yAeRBMYLf3V/kopcIetQQHYIkgW96LB9CmQABX9heoopsDK8tj5IZgz//dPqfYapm+S4mz8jIOFvIwmUle6iM2KdBvMGqIBKiURVoTwQZZMoWzZEqmaHFrRuNrZCDUJ8B3LmNBqp3UQtnYUuG2Vtg/q94Wqlv7nGiBJ/bT0HhPjrsFGXJs29F354rK3Xp9KeKO9RB2PYNgIJ22KFNOZ3IV67I5bd2uJQXHEuQYqAenHh/cIt1GicOVGHKr9RQOngz4093/tuVfiwhIyKZVWu4Xm3G8x6v9nyg4ifi5XSBNvXBCuXSdivv+yd
      yum_repos:
        rhel-7-server-rpms:
          baseurl: http://192.168.0.5/repos/rhel-7-server-rpms
          enabled: true
          gpgcheck: false
          name: Red Hat Enterprise Linux 7
        rhel-7-server-rh-common-rpms:
          baseurl: http://192.168.0.5/repos/rhel-7-server-rh-common-rpms
          enabled: true
          gpgcheck: false
          name: Red Hat Enterprise Linux 7 Common
        rhel-7-server-extras-rpms:
          baseurl: http://192.168.0.5/repos/rhel-7-server-extras-rpms
          enabled: true
          gpgcheck: false
          name: Red Hat Enterprise Linux 7 Extras
        rhel-7-server-optional-rpms:
          baseurl: http://192.168.0.5/repos/rhel-7-server-optional-rpms
          enabled: true
          gpgcheck: false
          name: Red Hat Enterprise Linux 7 Optional

# frontend.yml
